### PR TITLE
[DTSERWONE-1984] add privacy manifest

### PR DESCRIPTION
**Pull request by mwasdamji-hw-dev**
Add privacy manifest

* https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
* Address lint issue
* Bump up CI to run on latest Xcode version
* Fix broken unit test due latest Swift version

### CODE REVIEW

**Review by fzhang4-hw — DISMISSED** [review]

**Review by grmeyer-hw-dev — APPROVED** [review]
Great Job on fixing the Unit test and Lint issue

**Review by grmeyer-hw-dev — CHANGES_REQUESTED** [review]
It's missing these items,
- You need to add the `PrivacyInfo.xcprivacy` to `HyperwalletSDK.xcodeproj/project.pbxproj`
- Could you update the CHANGELOG.md ?

**Review by grmeyer-hw-dev — APPROVED** [review]
LGTM

**Review by dherreracarrillo-hw-dev — APPROVED** [review]

**Review by fzhang4-hw — APPROVED** [review]

**Comment by Mohammedalduhamshi** [comment]
> Add privacy manifest
> 
> 
> 
> * https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> 
> * Address lint issue
> 
> * Bump up CI to run on latest Xcode version
> 
> * Fix broken unit test due latest Swift version

**Pull request merged**
